version: '2'
services:
  web:
    build: .
    ports:
     - "4433:4433"
    links:
     - "redis"
     - "mongo"
     - "rabbitmq"
     - "elasticsearch"
  redis:
    image: "redis"
  mongo:
    image: "mongo"
  rabbitmq:
    image: "rabbitmq"
  elasticsearch:
    image: "elasticsearch"
